### PR TITLE
Added support for sigma

### PR DESCRIPTION
**Pull request by a-bezrukov**

### CODE REVIEW

**Comment by thebevrishot** [comment]
@a-bezrukov this's quite dangerous if we deploy this on production because because mainnet do not support sigma now.

**Comment by a-bezrukov** [comment]
@thebevrishot , Sorry, I didn't explain the purpose of this. This is just an adaptation to the Sigma release. I was gonna deploy when we release it to the mainnet. Could you review it to see if the Blockbook's standards are met and it'll be possible to merge it to the upstream, with the zcoin release details fixed? Also, am I right thinking that this is enough to adapt Blockbook to Sigma?

**Review by thebevrishot — APPROVED** [review]
@a-bezrukov OK, I got it. Just need to make sure we do not deploy it on production now LoL. Logic look good for me. Approved.

**Comment by a-bezrukov** [comment]
@thebevrishot, many thanks! I wait for a mainnet sigma release and then retest.

**Pull request merged**
